export const ROOM_ADDUSER = "ROOM_ADDUSER";

export const USER_JOINROOM = "USER_JOINROOM";
export const USER_SETROOMINFO = "USER_SETROOMINFO";
export const USER_PLAY = "USER_PLAY";
export const USER_SENDCHAT = "USER_SENDCHAT";
export const USER_RECEIVECHAT = "USER_RECEIVECHAT";
export const GAME_PLAY = "GAME_PLAY";
