export const ROOMJOIN = "ROOMJOIN";
export const ROOMJOIN_SUCCESS = "ROOMJOIN_SUCCESS";
export const ROOMJOIN_FAILURE = "ROOMJOIN_FAILURE";
export const ROOMLEAVE_SUCCESS = "ROOMLEAVE_SUCCESS";
export const ROOMLEAVE_FAILURE = "ROOMLEAVE_FAILURE";

export const USER_PLAY = "USER_PLAY";

export const GAME_PLAY = "GAME_PLAY";
