export const ROOMJOIN_REQUEST = "ROOMJOIN";
export const ROOMJOIN_SUCCESS = "ROOMJOIN_SUCCESS";
export const ROOMJOIN_FAILURE = "ROOMJOIN_FAILURE";
export const ROOMLEAVE_SUCCESS = "ROOMLEAVE_SUCCESS";
export const ROOMLEAVE_FAILURE = "ROOMLEAVE_FAILURE";

export const USER_JOINREQUEST = "USER_JOINREQUEST";
export const USER_JOINROOM = "USER_JOINROOM";
export const USER_PLAY = "USER_PLAY";
export const USER_SENDCHAT = "USER_SENDCHAT";
export const USER_RECEIVECHAT = "USER_RECEIVECHAT";
export const GAME_PLAY = "GAME_PLAY";

export const SERVER_JOINSUCCESS = "SERVER_JOINSUCCESS";
export const SERVER_BROADCASTCHAT = "SERVER_BROADCASTCHAT";