export const ROOMJOIN_REQUEST = "ROOMJOIN";
export const ROOMJOIN_SUCCESS = "ROOMJOIN_SUCCESS";
export const ROOMJOIN_FAILURE = "ROOMJOIN_FAILURE";
export const ROOMLEAVE_SUCCESS = "ROOMLEAVE_SUCCESS";
export const ROOMLEAVE_FAILURE = "ROOMLEAVE_FAILURE";

export const USER_JOINREQUEST = "USER_JOINREQUEST";
export const USER_JOINROOM = "USER_JOINROOM";
export const USER_GETROOM = "USER_GETROOM";
export const USER_SENDCHAT = "USER_SENDCHAT";

export const SERVER_JOINRESPONSE = "SERVER_JOINRESPONSE";
export const SERVER_BROADCASTCHAT = "SERVER_BROADCASTCHAT";
export const SERVER_BROADCASTROOMUPDATE = "SERVER_BROADCASTROOMUPDATE";